spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
#Redis????
redis:
  assist:
    bigkey:
      #???????key??
      auto: false
      #?key??????
      threshold: 1024 * 1024
      #?key???????
      count: 1000